name: Notify Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  notify-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Vercel
        uses: vercel/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: vercel-deployment
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'